week2/airports/urls.py
# Load path from django.url
from django.contrib import admin

# load this application from views.py
from django.urls import path

from . import views

# define URL pattern
urlpatterns = [
    # get index view
    # Starting with airports/
    path('', views.index),

    # Show import info by code
    # uri /airport/MYR
    # airport parameter in URL matches airport_info function
    path('<str:airport_code>', views.airport_info),
]

week2/csci409/urls.py
from django.contrib import admin
from django.urls import include, path

import airports.views
import flights.views
import routes.views
import tickets.views

urlpatterns = [
    path('', airports.views.index),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('airports/', include('airports.urls')),
    path('routes/', include('routes.urls')),
    path('flights/', include('flights.urls')),
    path('tickets/', include('tickets.urls')),
]

week2/routes/urls.py
# Load path from django.url
from django.contrib import admin

# load this application from views.py
from django.urls import path

from . import views

# define URL pattern
urlpatterns = [
    # get index view
    # Starting with airports/
    path('', views.index),

    # Show import info by code
    # uri /flight/search/MYR/ATL
    # airport parameter in URL matches airport_info function
    path('search/<str:origin>/<str:destination>', views.route_search),
]

week2/airports/models.py
from django.db import models


# Create your models here.
class Airport(models.Model):
    name = models.CharField(max_length=255)
    airport_code = models.CharField(max_length=3)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=2)
    zipcode = models.CharField(max_length=5)
    is_open = models.BooleanField()


class Runway(models.Model):
    LEFT = 'L'
    CENTER = 'C'
    RIGHT = 'R'
    NONE = 'N'
    RUNWAY_DESIGNATION_CHOICES = [
        (LEFT, 'Left'),
        (CENTER, 'Center'),
        (RIGHT, 'Right'),
        (NONE, 'None'),
    ]
    runway_number = models.IntegerField()
    runway_designation = models.CharField(
        max_length=1,
        choices=RUNWAY_DESIGNATION_CHOICES,
        default=NONE
    )
    length = models.IntegerField()
    width = models.IntegerField()
    airport = models.ForeignKey(Airport, on_delete=models.CASCADE)

week2/airports/views.py
from django.http import HttpResponse

from flights.forms import FlightForm

from tickets.forms import TicketForm
from tickets.models import Reservation
from .models import Airport
from django.shortcuts import render


def index(request):
    airports = Airport.objects.all()
    context = {'airports': airports}
    return render(request, 'airports/index.html', context)
    # airport_list = ', '.join([a.airport_code for a in airports])
    # return HttpResponse('Showing all airports: ' + airport_list);


# Create your views here.
def airport_info(request, airport_code):
    airport = Airport.objects.get(airport_code=airport_code)
    context = {'airport': airport}
    return render(request, 'airports/airport.html', context)
    # airport = Airport.objects.get(airport_code=airport_code)
    # return HttpResponse('Showing info for airport: ' + airport.name + '- ' + airport.airport_code)

week2/airports/templates/airports/airport.html
<!-- Specify which template to extend -->
{% extends 'base.html' %}

<!-- Add content to the content block in the main template -->
{% block content %}
<!-- Q1. Inside the h1 tag display the airport_code- airport name -->
<h1></h1>
<!-- Display the airport address -->
<h2>Address</h2>
<p></p>
<h2>Runways</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Runway</th>
            <th scope="col">Length</th>
            <th scope="col">Width</th>
        </tr>
    </thead>
    <tbody>
        <!-- Q3 Display the runway number along with designation L,C,R, etc. -->
        <!-- Runway length and width  in a table row-->
        {% for runway in airport.runway_set.all %} <!-- this is a new type of object it will fetch all of the associated runways -->

        {% endfor %}
    </tbody>
</table>
{% endblock %}

week2/airports/templates/airports/index.html
<!-- Specify which template to extend -->
{% extends 'base.html' %}

<!-- Add content to the content block in the main template -->
{% block content %}
<h1>Airports</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Airport Code</th>
            <th scope="col">Airport Name</th>
            <th scope="col">More Information</th>
        </tr>
    </thead>
    <tbody>
        {% for airport in airports %} <!-- Loop through airports from the context variable specified in views.py -->
            <tr>
                <td>{{ airport.airport_code }}</td>
                <td>{{ airport.name }}</td>
                <td><a href="/airports/{{ airport.airport_code }}">More Information</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}